### ISSUE TITLE
Create turret component

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycubehammer#2]
Slewing ring driven by neo550 through versa gearbox.
Limit switches at end of rotation.

**Comment by LucienMorey** [comment]
Some additional information:

- This will likely only have a relative encoder on it, so it will not know where it is until it indexes (This is how the arm extension worked on the main robot for this year). We used the retracted limit switch to index the system so it could operate using an absolute position. We can do the same thing here with the limit switches on either side of the rotation.
- So that we can easily target all the goals in the grid, we will need to be able to specify an absolute angle to point at (This means that it will need to index itself before it can be used properly)
- It will need a check if it is at angle or is ready to be parsed back up to state machines and controllers for higher-level orchestration

Some rough pseudocode is here that you guys can use and actually implement is here:
```python
class Turret:
  GEAR_RATION: float
  ANGLE_ERROR_TOLERANCE: float
  
  motor: Neo550 #This will need to change to the proper motor controller type
  positive_limit_switch: Digital I/O
  negative_limit_switch: Digital I/O # These could also be attached directly to the motor controller breakout board for interrupts

  goal_angle = 0.0

  def __init__(self) -> None:
    # Create the hardware object handles

    # set index found var to false
    pass

  def set_angle(self, angle: float) -> None:
    # set the desired angle for the turret

    # You will need to check the documentation if this can be on the output shaft 
    # or if you need to convert the angle back to a motor angle with the gear ratio
    pass

  def at_angle(self) -> bool:
    # return abs(current angle - reference) < Tolerance 
    # This could also be done inside the motor controller depending on how it works
    pass

  def find_index(self) -> None:
    # configure turret to rotate until it finds an index 
    # probaly speed or voltage for this
    pass

  def execute(self) -> None:
    
    #if index found:
      # calculate pid output based off angle delta
      #calcualte feed forward based off angle delta
      # clamp input
      # set motor setpoint
    #else:
      # set desired output voltage or speed to find index
    pass
    
```
